### ISSUE TITLE
differentcars: Display different kind of cars

### ISSUE THREAD

**Issue by iroq** [TheWaypointers/TrafficSimulator#49]
Different looks for the different car behaviours and ambulance

**Comment by mengzhuwang** [comment]
We now use different color to distinguish different car behaviors and ambulance. Do you mean I should draw them in different shape? @iroq

**Comment by iroq** [comment]
Oh, we do already? That's good. Then we should add some explanation which color is which vehicle, maybe we can do this in #58 . I'll close for now.

**Comment by mengzhuwang** [comment]
in MapPanel, we defined VEHICLE_CarNormal_COLOR = Color.blue, VEHICLE_CarCautious_COLOR = Color.yellow; VEHICLE_EmergencyService_COLOR = Color.white; VEHICLE_Bus_COLOR = Color.cyan; VEHICLE_CarReckless_COLOR = Color.red; @iroq

**Comment by iroq** [comment]
Yes, i meant some explanation displaying in the GUI so the user can know what kinds of vehicles they're looking at.

**Comment by mengzhuwang** [comment]
aha, I see, fine @iroq
