### ISSUE TITLE
Incorrect directions of roads in simulation

### ISSUE THREAD

**Issue by iroq** [TheWaypointers/TrafficSimulator#73]
While fixing #69, I noticed that the simulation has wrong directions of some (or all) horizontal roads. For example `(E3 : A)` has direction `Down`, while according to `complex.xml` it should be `Right`. Fixing this is needed for me to complete #69. Is this one of the bugs you've encountered in #67? @yzzmh123

**Comment by vezer1993** [comment]
actually in that version it doesn't matter, i fixed this in the new branch with the analyse junction... I was aware of this :)

**Comment by iroq** [comment]
Can you make a pull request with just that fix so I can continue working?

**Comment by vezer1993** [comment]
yes

**Comment by iroq** [comment]
closed by #74
